### ISSUE TITLE
Failed to run yak on Windows 10

### ISSUE THREAD

**Issue by peascod** [exxeleron/enterprise-components#57]
Tried to set up and run the tutorial on a Windows 10 x64 machine but stucked at running the yak command.

D:\KDBEnterpriceComponent\DemoSystem>yak restart \*
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__yak__.py", line 30, in <module>
  File "osutil/__init__.py", line 46, in <module>
  File "osutil/_win32.py", line 17, in <module>
  File "psutil/__init__.py", line 110, in <module>
  File "psutil/_pswindows.py", line 16, in <module>
  File "psutil/_psutil_windows.py", line 26, in <module>
  File "psutil/_psutil_windows.py", line 17, in _bbfreeze_import_dynamic_module
ImportError: DLL load failed: The operating system cannot run %1.

The error message seems to indicate that the pstuil library failed to be loaded.  Any idea?

**Comment by chenkangcrack** [comment]
I also come across this problem!!

**Comment by chenkangcrack** [comment]
I also have the same problem, have you resolved this already? @peascod
